## CANCER CLASSIFICATION USING GENE EXPRESSION DATA

In [27]:
import pandas as pd

In [28]:
from sklearn import preprocessing

In [29]:
import numpy as np

In [30]:
data = pd.read_csv('leukemia.csv')

In [31]:
data.head()

gene  AFFX-BioC-5_at  hum_alu_at  ...  L49218_f_at  M71243_f_at  Z78285_f_at
0  ALL              88       15091  ...           36          191          -37
1  ALL             283       11038  ...           11           76          -14
2  ALL             309       16692  ...           41          228          -41
3  ALL              12       15763  ...          -50          126          -91
4  ALL             168       18128  ...           14           56          -25

[5 rows x 5148 columns]

In [32]:
print(data.values)

[['ALL' 88 15091 ... 36 191 -37]
 ['ALL' 283 11038 ... 11 76 -14]
 ['ALL' 309 16692 ... 41 228 -41]
 ...
 ['AML' 146 15689 ... -2 210 16]
 ['AML' 431 41570 ... 0 284 -73]
 ['AML' 9 39538 ... 20 379 -60]]


In [33]:
dict = {'gene': 'Type'}

In [34]:
data.rename(columns = dict, inplace = True)

In [35]:
data.head()

Type  AFFX-BioC-5_at  hum_alu_at  ...  L49218_f_at  M71243_f_at  Z78285_f_at
0  ALL              88       15091  ...           36          191          -37
1  ALL             283       11038  ...           11           76          -14
2  ALL             309       16692  ...           41          228          -41
3  ALL              12       15763  ...          -50          126          -91
4  ALL             168       18128  ...           14           56          -25

[5 rows x 5148 columns]

### Checking to see if there is any missing values or not

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 5148 entries, Type to Z78285_f_at
dtypes: int64(5147), object(1)
memory usage: 2.8+ MB


In [37]:
data.describe()

AFFX-BioC-5_at    hum_alu_at  ...  M71243_f_at  Z78285_f_at
count       72.000000     72.000000  ...    72.000000    72.000000
mean       189.347222  25209.180556  ...   433.486111   -30.569444
std        111.884014  10882.622106  ...   623.918444    40.192434
min        -36.000000   6479.000000  ...   -68.000000  -190.000000
25%         99.500000  17783.250000  ...   123.500000   -54.750000
50%        179.000000  21972.000000  ...   218.000000   -28.500000
75%        277.750000  30856.250000  ...   373.000000    -3.750000
max        431.000000  58203.000000  ...  3193.000000    78.000000

[8 rows x 5147 columns]

### Replacing categorical values with numaric value 

In [38]:
label_encoder = preprocessing.LabelEncoder()

In [39]:
data['Type'] = label_encoder.fit_transform(data['Type'])

In [40]:
print(data.values)

[[    0    88 15091 ...    36   191   -37]
 [    0   283 11038 ...    11    76   -14]
 [    0   309 16692 ...    41   228   -41]
 ...
 [    1   146 15689 ...    -2   210    16]
 [    1   431 41570 ...     0   284   -73]
 [    1     9 39538 ...    20   379   -60]]


### Train-Test Split 

In [19]:
# def split_train_test(data, test_ratio):
#     np.random.seed(42)
#     shuffled = np.random.permutation(len(data))
#     print(shuffled)
#     test_set_size = int(len(data) * test_ratio)
#     test_indeces = shuffled[:test_set_size]
#     train_indeces = shuffled[test_set_size:]
#     return data.iloc[train_indeces], data.iloc[test_indeces]

In [41]:
# train_set, test_set = split_train_test(data, 0.2)

In [42]:
# print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}")

In [43]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data, test_size = 0.2, random_state = 42)

In [44]:
print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}")

Rows in train set: 57
Rows in test set: 15


In [45]:
train_set.head()

Type  AFFX-BioC-5_at  hum_alu_at  ...  L49218_f_at  M71243_f_at  Z78285_f_at
22     0             -36       36417  ...            9          243           36
56     0             270       49419  ...          -43          702           18
49     0             129       29906  ...           -4          176           40
33     1             193       26052  ...            6         2484           -2
39     0             295       20958  ...          -33          -33          -21

[5 rows x 5148 columns]

In [46]:
test_set.head()

Type  AFFX-BioC-5_at  hum_alu_at  ...  L49218_f_at  M71243_f_at  Z78285_f_at
4      0             168       18128  ...           14           56          -25
62     1             319       31068  ...            0          196           20
18     0             207       20225  ...          -50          333          -24
0      0              88       15091  ...           36          191          -37
28     1             132       45492  ...           28         1558          -67

[5 rows x 5148 columns]

### Looking for correlations 

In [47]:
%matplotlib inline

In [48]:
import matplotlib.pyplot as plt

In [51]:
data

Type  AFFX-BioC-5_at  hum_alu_at  ...  L49218_f_at  M71243_f_at  Z78285_f_at
0      0              88       15091  ...           36          191          -37
1      0             283       11038  ...           11           76          -14
2      0             309       16692  ...           41          228          -41
3      0              12       15763  ...          -50          126          -91
4      0             168       18128  ...           14           56          -25
..   ...             ...         ...  ...          ...          ...          ...
67     1             141       22818  ...          -22          260            5
68     1              95       39323  ...            0         1777          -49
69     1             146       15689  ...           -2          210           16
70     1             431       41570  ...            0          284          -73
71     1               9       39538  ...           20          379          -60

[72 rows x 5148 columns]

In [50]:
data.corr()

Type  AFFX-BioC-5_at  ...  M71243_f_at  Z78285_f_at
Type            1.000000        0.287339  ...     0.331383     0.038181
AFFX-BioC-5_at  0.287339        1.000000  ...     0.239874     0.012820
hum_alu_at      0.164153       -0.018406  ...     0.122600     0.017043
AFFX-DapX-M_at  0.077598        0.048785  ...     0.111680     0.203480
AFFX-LysX-5_at -0.051750       -0.202527  ...    -0.058768     0.097755
...                  ...             ...  ...          ...          ...
X83863_at       0.132817        0.279403  ...     0.372747     0.068155
Z17240_at      -0.000371        0.202633  ...    -0.005976     0.046329
L49218_f_at    -0.129777        0.055843  ...     0.043819     0.239192
M71243_f_at     0.331383        0.239874  ...     1.000000     0.007287
Z78285_f_at     0.038181        0.012820  ...     0.007287     1.000000

[5148 rows x 5148 columns]

In [26]:
corr_matrix = data.corr()
corr_matrix['Type'].sort_values(ascending=False)

### Selecting a desired model

In [ ]:
X_train = train_set.drop("Type", axis = 1)
y_train = train_set["Type"]

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
X_test = test_set.drop("Type", axis = 1)
y_test = test_set["Type"]

In [ ]:
model.predict(X_test)

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.model_selection import cross_val_score
cvs = cross_val_score(model, X_train, y_train, cv = 3, scoring = "accuracy")

In [ ]:
cvs.mean()

0.9473684210526315

In [ ]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(model, X_train, y_train, cv = 3)

In [ ]:
y_train_pred

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

### Calculating confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_train, y_train_pred)

array([[35,  1],
       [ 2, 19]], dtype=int64)